import { vi } from "vitest";

// Throwaway RSA keypair generated by scripts/generate-auth-keys.mjs, used
// ONLY by tests that exercise full Convex Auth sign-in flows (token
// generation requires JWT_PRIVATE_KEY + JWKS). Never deployed anywhere.
const TEST_JWT_PRIVATE_KEY =
	"-----BEGIN PRIVATE KEY----- MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrId3ZZR8iejZP PP9nWtB14jzrA+oO9cx1LIeSV8UZmVq7vY5KNX9qzHwdAt0T2b/p/m1Fsse4vnY+ +eKwuhdaj3E/Qbf8VdHcrB0h1uGbBYL+BGkuecg0kk9pDUXS8hp3Ab1rhUMmqrKz FtV99zSgRzkDBMTPYEaSdTFv3DxGi65khd+tBiB0O70oj2WJ4oSwXWXxeVTcpbs2 Jp1Q1y2A9zMZp1BSHjcFhpKwPMixugO1z6eo1T14TdklYqmoOgjwDpeTd5yhDGqd RLPMnqHjTjzW1v2ze1gZUfyEasw74iM/WPU9diAjI2UsOISaKruQmBehMzs0UUSe Ot4zPLKPAgMBAAECggEAVHuEG3n13F3r6MNKrNni1odpHnZQurDyjhf9F6xXw9L2 vX8POyhc7jrjvKi4vj99pEUz6bggK95u3pkbJbbAp7bvp9RIQXyWfXPEb/u2ZYLb j45a5JQ/V2CxbkGcqk5V7VFBE072/yQ+0vWfUK/U3Zk7lndot52mSVAspzXY1dP5 fMKTq4v8z5ERS7S7IqXZBqwNHwDjCndyMA8nMIejWr1BtZqWYOn0BibiRzsrNsmc mrke9icUEZTMZADsr7WQy0X1E8Pro8ay1guVxk1pE80wxUCeku729V9EH3G4KUH8 z0NLbDKfzbPF1Sh/tduGfX59U/pb1FBrxr5FJeklZQKBgQDWSE9D51ZyURJuMuEe H1wMDFomiDGlnSQFKucoMRvJrC0HfgypokB0QEmxAefwIVzURz6CPsSuJwHGFkz3 E+9azxspmLZl2k4ayxl+IBvixu176pudQoqFdC/P3Jy/caiArExrMZaddp2SJM92 y0OBixkNm3QxYeP6tBK3MnaFuwKBgQDMcvt2YVp1c3yrLcPXj4xleu0K6y9WUM/G h5+JwzMWrjL7HdrYmoHuhriehJvXlEMoXQHU8/YG9GWAdL1AyoveOACS166k1Lz0 MvvhxgsOw+WxRao0ryMn2mMtKQTL3QUzpVSHzZ/We0MnDqfabtKemCP0a9xXGFAZ NRm/k3yvPQKBgA/zBeNZ/rc3jZWiN9tUHjfPW45uqLNZBOtVjCsTrKvQIvHh0fN2 XjHI7zM7nxXihdRPEToEjgMgaCNkWYoyc6hgrfbkpP7jxth7sYQPw8OXZunIRpjn 8QOJ6F0iYJBnV1Fsgaug30MNJyFPmBmRe47S2aSHo5hhXuS0LohwOx4tAoGBALOY ZfEtv+rg0ikFAL6BKRGUFFq9Ek4+muaJCMpZoK1RxRL2vOH9iBniWpdVYhjT8tKo MQ3CaOLfGbLn2b/qrUc95rMXqCC/iGTzzHQeJmSIDWPWEJhLKRS/MNPg7oeu1fzy RPku1jPw/6J1q1mkdHxApYT2ow4XG3WpQb8abjL5AoGAX1BbMNl1zZjgya8CnEoS qPky20ZwSECRhUtzm4LDCfYFYZ5Yh9jEFTeMewwTDm4LNJmPy8JaishXekM1ToUX SCsDw7WuzvlGBkM3TzNDEAMd/nADrreVKFSvw5AnXVSo75YlsBIihgpntV8Nc8y/ q4ifG1I5mzEEM3adcrpj8l4= -----END PRIVATE KEY-----";

const TEST_JWKS =
	'{"keys":[{"use":"sig","kty":"RSA","n":"qyHd2WUfIno2Tzz_Z1rQdeI86wPqDvXMdSyHklfFGZlau72OSjV_asx8HQLdE9m_6f5tRbLHuL52PvnisLoXWo9xP0G3_FXR3KwdIdbhmwWC_gRpLnnINJJPaQ1F0vIadwG9a4VDJqqysxbVffc0oEc5AwTEz2BGknUxb9w8RouuZIXfrQYgdDu9KI9lieKEsF1l8XlU3KW7NiadUNctgPczGadQUh43BYaSsDzIsboDtc-nqNU9eE3ZJWKpqDoI8A6Xk3ecoQxqnUSzzJ6h40481tb9s3tYGVH8hGrMO-IjP1j1PXYgIyNlLDiEmiq7kJgXoTM7NFFEnjreMzyyjw","e":"AQAB"}]}';

/** Stubs the env Convex Auth needs to mint tokens in full sign-in flows. */
export function stubAuthTokenEnv() {
	vi.stubEnv("JWT_PRIVATE_KEY", TEST_JWT_PRIVATE_KEY);
	vi.stubEnv("JWKS", TEST_JWKS);
	vi.stubEnv("SITE_URL", "http://localhost:3000");
	vi.stubEnv("CONVEX_SITE_URL", "http://localhost:3211");
}
